export const filters = [
  "All",
  "Technical",
  "Cultural",
  "Sports",
  "Free",
  "Activity Points",
  "Hackathon",
  "Workshop",
];
export const events = [
  ,{
    name: "DSA guidance",
    club: "CODE IO",
    date: "10/09/25",
    time: "2:00PM",
    location: "Lab",
    activityPts: 5,
    duration: "2 hrs",
    fees: 120,
    category: "Technical",
    registeredUsers: 48,
    totalUsers: 50,
  },
  {
    name: "Journey from dsa to Competitive Programming",
    club: "Protocol",
    date: "12/09/25",
    time: "4:00PM",
    location: "Lab",
    activityPts: 3,
    fees: 0,
    duration: "2 hrs",
    category: "Technical",
    registeredUsers: 42,
    totalUsers: 50,
  },
  {
    name: "Drone genesis",
    club: "Elsoc",
    date: "11/09/25",
    time: "10:00AM",
    location: "Lab",
    activityPts: 0,
    duration: "6 hrs",
    fees: 2000,
    category: "Workshop",
    registeredUsers: 41,
    totalUsers: 50,
  },
  {
    name: "Classical Singing Compeitions",
    club: "Ninaad",
    date: "24/09/25",
    time: "3:00PM",
    location: "Audi 1",
    activityPts: 0,
    duration: "3 hrs",
    fees: 50,
    category: "Non technical",
    registeredUsers: 34,
    totalUsers: 50,
  },
];
export const clubs = [
  {
    name: "Code IO",
    position: "Technical head",
    img: "codeIO.jpg",
    events: 14,
    people:300,
  },
  {
    name: "Augment AI",
    position: "Social media head",
    img: "augmentAi.jpg",
    events: 11,
    people:120,
  },
  {
    name: "Protocol",
    position: undefined,
    img: "codeIO.jpg",
    events: 21,
    people:130,
  },
];
